version: '3.8'

services:
  stable-diffusion:
    build:
      context: . # This refers to the repository root
      dockerfile: Dockerfile # Name of the Dockerfile
    container_name: stable-diffusion
    command: python /app/scripts/stable_diffusion.py
    volumes:
      - .:/app # Mount the current directory into the container
    ports:
      - "5000:5000" # Adjust as needed
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
